apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgB5KatB7Q3WbSVNhxfs3/rBQfO0X6FpSPoD5PhGtqIeCsmzbpAYX+aADi9s6/eCvFBCaTzQjx7xj93loBcMopAemfzq5yIAE1tBhAL9UYMP0yzBOsSbql2tagZvcjvx0TC6XYU7OzWs5AkM6r/kHR6ttGOZMacIuYndZEcy3zkwrf8ugUPIEMn072v2FMTWahdKBA3bgrGrIEXheOYV/C35NJR58JvukmCz41Ym3q1CH57H0BD1Q9EypTJ/vPC//Dq+vreLQWBlpdOdsEz5nSX9yu8WrcDHi4qnOMG9wtV2e50yP+SD6yz6fuo5dC7wEmSMeStS7R/GtMZLl6LnBO/44X6zim2RDLWN6N9NepFwCTyaGkhc2YfKfV1ujjbF3PjQbbWF2lckw7sn2mVM6EdNj3cdxRMjCOVf8PH0twbHXJTje4cXvjtFLizWb8M9QJlBphMnZdIsYRP0xNFK8rG7exig2omeb5Ja77loDjjAqWRvPdca+HQDmZq8iUPJOrI2U68xrNrOCL/uOemcmo4QxTdayfcNXDnP9EChKNG0Sm2qwuYunoZGC1vW1sk5qW6VgLNapnt6wUpUJpZhct4SAC5EA7AGvYX/TctY2i/1vISTC0tU7TnXrcyo2rv0D2vYOPwyPsjdzeFIbqhvXKIW5uTxezEYFXsxSC8Z8HT9f72HKdBbp2PjJ8Af8ctkf9eVjhAIqYMa4+7/lWoNjuQ83KUdxTDxSF54EcOfMlwpDSi5dMK4VKoY
    username: AgCy3ZfL/yRl0JMytJsFOw6pgSvsuGdLEfFnLlyayfkbBdi1pvnwGq9wmd4OzUx/8lR/XPPjw/XFr6CPkAFXCE7G3StbJVKH83SWl7vxiC4+u/eO3ATOhnFReSMA/CFTGOqhy0oh+KNXwpwHGAdQVboh/QYvjUduGTdO0aePEvOyTC1KS6ADljIy0siDMjWnebSWtW6EK8Hbl3gHegZN0t44D8Kcej9URnXK8nalHs+uFWBWTf5C/6ncbfAtM+oxfCz1NKZsKyzU6HW8kqIzoMqU3AlbqSMBrGgs9nzenR++gjG2Eyv1AgzyOvckWcQTbgjaHVDa7eRAzDertorsxlZGNM3qRaajhOpFYMRVg2gxZMXwKGNEH/rN6ZKjnWTe3fhH7rIX+Ddn2fNjbjlJsMGCHGpi3asyxmAdMiEr8pnW+xNqcTC1DSKRt+76BQMBCZ8lTHIFUKCqqwmi+QNlKPgwEeXS2JVeGyGuQPFNEKrI6SOSEuVutQ1L0ISJt2ihifQq1rIQQIFI7ultLPrZtChr168c2sjjEnpRjYSeueO6M/gz8l478KwpF763pVu/PiN8vti1QpV8BWm0hX/wIwhgYPujAYT1YyOeQ1YED0cJaGKBFAGh3lmx+wLAG8aBMU4eiTAk3KAOT1pRzOPSVEbbYt0oeKdeLs3/RjrJcxi6NZgkIoQggLb0RC3QdkNL9QJYQwjafJYTfp7Pkvxd5BD6iGYA
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

