apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCcRxmORNwtlUcRklptVdLsQfP3qbAISuVr09bdRol+wFU2zQXz7EUbtXKzY0z3VhOQp7J8Pq0Ck003OxWCGWnkl1BTTfZsPF4ViIWSpwwBReVMYvEuWLQ3m95m9hz5bML+aHUggTQbWc4x2dkCX3oF8IxHeFlgKYQvvT37PCnusjk+ElcpsB8k8aJESBmY7ECKCjpxmSRBEPJPexjyk7nzjhv7qdOl1LEaoO/8o34oRxkcVUZjq9PwUVFGXPsOuWMGcIaZu7sj+Q8xGiOhzVq4v5/7GbrYenLNkACyM5VmOG9nwG+3Uo3YmPkBHAMetKna4TUiCZKS4lqZmtxjTU/3Gx2Ks1RBi3w22jb0yYF0RaE3L3ykbwifnOPg1umQQ27ymhCQHjhliZ6NBD1glRdzc4qTwAnZX6olNU5YRTvRBL5K+VSjzYVs7NQjgQF/FaRYmHRwRfuwLUuHddZXrNdglxTEOCqdalab3dTkDcILaUdOXceK6+uaXZZHRMjkNVTl+YQ4SzZ4bpaoGxl2q88AtcM9mKyHyEaRT86uVt2FtgsoFE+R8oUqqYTgeGf68omjgc4LVUTBEftz7YkVMUQkHjBOqoqiXw4rcF7FVLdxsnFhGW+yGmKMELNl5aIddxqzW2W4uNSuPqNVowXqVRW1ofUhujlNp60xDIEw2UttXL9F9fdnhB9510ehbuvE9METNd+pxGb3xLuDrAzO+xF6eUd3AIlg4dYohAFpzrEeJAg/pXKHjILHrTgaHWmRWOQNP5F9tGLRJMjoBqtkj1q00DkXTqYcKHBuCGWUt5jy+8XiprJB/Zs1J7shtQIuw3TgU0vQvVQm6s/8J5iOTeBYmQ/A9YPXZ0iKtbpyUcwutN9m0W8q5fEMInH/0QUUQjN42pTXLJIiyQWcD37B6vNVo6kw1LnNoWI60b4LUD8L+o8VxzxSRiQIZwhp/ItwFwo=
    IBM_ENTITLED_REGISTRY_USER: AgC9Vs1r2HGNlkX6bOd1Bb6iBGNmRxQ1VQlcLtxDfc6J72YLqxnh8h9R4BTYYPSAJ5aIxn71m3uctTZ/FJJkbGiMklrJIqhhSBFwsKdnjyiAZwJZFz6XnnZ5i40x/luGO3Eqau8x9bwSMh6Ipnb1FPd8IyVjqjTdePvl5Tdk+P/I2mFkdnh3iUU5jFYVb1Cf/3m5U760KJTOSi9rdLNcXYQMxTcmPCbEliwiEvwOHkSatorGYu4oOAYMo/qngf+Elgd4PHfQBNKU3WVm0QmutIJt0JaARcFkWR4ETtyuspFbuFqhTC4AuH4aSCNRDSE1RTHkcbhcEf2ry+Cm7C+KSTCTdBnL/v/DJtz8GPeusSg/65fwKRcyjLxd/hsyVqMlnrKe1G5W08ENaIs2DVwOytiLfcVWFzzbMAznP6GJvJ8zXTrDwIAwdWlq+lGICcbq+ESNj2XjDbXc5PdKsk70JD9M0mAQK/EjbD3H+3QvmWsPn3FWs77KKBrq11FsVbEaGIHb1mwkqZ9rDELq+5+ErpiASGMyjN4omDMRxl9ZZWtm4vmq1TWUqn8GC7rHDqHzhRKEDRvpdJA1Mpp6kpNpdxtXaKE+cD7/e0DolnpTK9cwIASekWflpnR7u0c1a+SQVIwkw2dwUjexwNVVlmKnvHh8Q+4/wBb0Tf1hJCoM66uFtVYxcOmBuqEEODo8h7ZgdhhXbA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

